# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: pvecsictl

before:
  hooks:
    - go mod download

dist: bin
builds:
  - dir: cmd/pvecsictl
    binary: pvecsictl-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - binary
    name_template: "{{ .Binary }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: edge

# dockers:
#   - use: buildx
#     image_templates:
#       - ghcr.io/panzer1119/pvecsictl:{{ .Version }}-amd64
#     goos: linux
#     goarch: amd64
#     build_flag_templates:
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       - "--target=pvecsictl-goreleaser"
#       - "--platform=linux/amd64"
#   - use: buildx
#     image_templates:
#       - ghcr.io/panzer1119/pvecsictl:{{ .Version }}-arm64
#     goos: linux
#     goarch: arm64
#     build_flag_templates:
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       - "--target=pvecsictl-goreleaser"
#       - "--platform=linux/arm64"
# docker_manifests:
#   - name_template: ghcr.io/panzer1119/{{ .ProjectName }}:{{ .Version }}
#     image_templates:
#       - ghcr.io/panzer1119/{{ .ProjectName }}:{{ .Version }}-amd64
#       - ghcr.io/panzer1119/{{ .ProjectName }}:{{ .Version }}-arm64

homebrew_casks:
  - name: pvecsictl
    directory: Casks
    homepage: https://github.com/panzer1119/proxmox-csi-plugin
    description: "Proxmox VE CSI Mutate tool"
    license: Apache-2.0
    # conflicts:
    #   - formula: pvecsictl

    commit_author:
      name: panzer1119
      email: 5407715+panzer1119@users.noreply.github.com
    repository:
      owner: panzer1119
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TOKEN }}"

    binaries:
      - pvecsictl
    custom_block: |
      arch arm: "arm64", intel: "amd64"
      os macos: "darwin", linux: "linux"
      binary "pvecsictl-#{os}-#{arch}", target: "pvecsictl"

    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pvecsictl-darwin-#{arch}"]
          end
